### ISSUE TITLE
What Framework Should we use?

### ISSUE THREAD

**Issue by Yu14Y** [Techwise-fun/techwise.fun#1]
I was thinking astro? https://astro.build/
what do you guys think? @Techwise-fun/co-owner ?

**Comment by Tr0llie** [comment]
I was thinking React
Idk about u but i have no idea how astro works lol

**Comment by Yu14Y** [comment]
> I was thinking React Idk about u but i have no idea how astro works lol

If i am being honest, i really dont want to learn a new framework, what about @gx-andrew

**Comment by gx-andrew** [comment]
> > I was thinking React Idk about u but i have no idea how astro works lol
> > > If i am being honest, i really dont want to learn a new framework, what about @gx-andrew

For me, Astro is fine, Astro is fast and good for this. I don't think react is good for this as astro is fast compared to react and astro is static rendering rather than dynamic render which is pretty neat and simple for what we are making as of now.
Also Astro is simple xD 


Followup question @Yu14Y, Why don't we make this on gitlab, i don't like github

**Comment by Tr0llie** [comment]
> > > I was thinking React Idk about u but i have no idea how astro works lol
> > > > If i am being honest, i really dont want to learn a new framework, what about @gx-andrew
> 
> For me, Astro is fine, Astro is fast and good for this. I don't think react is good for this as astro is fast compared to react and astro is static rendering rather than dynamic render which is pretty neat and simple for what we are making as of now. Also Astro is simple xD
> 
> Followup question @Yu14Y, Why don't we make this on gitlab, i don't like github

It's not that deep, the page loading difference is like .5 sec only :skull: 
anyway if @Yu14Y choses astro, i cant help much anyway

**Comment by gx-andrew** [comment]
> > > > I was thinking React Idk about u but i have no idea how astro works lol
> > > > > If i am being honest, i really dont want to learn a new framework, what about @gx-andrew
> > 
> > 
> > For me, Astro is fine, Astro is fast and good for this. I don't think react is good for this as astro is fast compared to react and astro is static rendering rather than dynamic render which is pretty neat and simple for what we are making as of now. Also Astro is simple xD
> > Followup question @Yu14Y, Why don't we make this on gitlab, i don't like github
> 
> It's not that deep, the page loading difference is like .5 sec only 💀 anyway if @Yu14Y choses astro, i cant help much anyway

.5 sec is .5 sec, it is faster compared to react

**Comment by Tr0llie** [comment]
@Yu14Y are u gonna buy a hosting service for this or r u jus gonna use the same old boring vercel

**Comment by gx-andrew** [comment]
> @Yu14Y are u gonna buy a hosting service for this or r u jus gonna use the same old boring vercel

U wanna create a new issue for this?
i wanna make some suggestions

**Comment by Tr0llie** [comment]
> > @Yu14Y are u gonna buy a hosting service for this or r u jus gonna use the same old boring vercel
> 
> U wanna create a new issue for this? i wanna make some suggestions

ok sure

**Comment by Yu14Y** [comment]
@Techwise-fun/co-owner 
We are going to use astro, As @gx-andrew & @Yu14Y  agreed to use astro and only one dis-agree, we will be using astro
