### ISSUE TITLE
What are we using for deployment and hosting?

### ISSUE THREAD

**Issue by Tr0llie** [Techwise-fun/techwise.fun#2]
suggestions
- vercel
- netlify

**Comment by gx-andrew** [comment]
i was thinking a  self hosted https://coolify.io/ ?

**Comment by Tr0llie** [comment]
> i was thinking a self hosted https://coolify.io/ ?

ok and ure gonna ask me to host that on my servers aren't u?

**Comment by gx-andrew** [comment]
> > i was thinking a self hosted https://coolify.io/ ?
> 
> ok and ure gonna ask me to host that on my servers aren't u?

quite the opposite, i have some space left in my vps

**Comment by Tr0llie** [comment]
> > > i was thinking a self hosted https://coolify.io/ ?
> > 
> > 
> > ok and ure gonna ask me to host that on my servers aren't u?
> 
> quite the opposite, i have some space left in my vps

yeah last time u setup a service on my vps, u broke my Nextcloud office and messed up the file syncing thing

**Comment by gx-andrew** [comment]
> > > > i was thinking a self hosted https://coolify.io/ ?
> > > 
> > > 
> > > ok and ure gonna ask me to host that on my servers aren't u?
> > 
> > 
> > quite the opposite, i have some space left in my vps
> 
> yeah last time u setup a service on my vps, u broke my Nextcloud office and messed up the file syncing thing

It was like 2 year ago!! forget it

**Comment by Tr0llie** [comment]
What about Firebase, they are pretty good ngl

**Comment by gx-andrew** [comment]
Tbh regardless of what we chose, they all do the same job, just choose one and get over it. I do prefer coolify as it offers 100% control

**Comment by Tr0llie** [comment]
> Tbh regardless of what we chose, they all do the same job, just choose one and get over it. I do prefer coolify as it offers 100% control

@Yu14Y Respond to us man, coolify is not cool-li-fying at all!

**Comment by Yu14Y** [comment]
@Techwise-fun/co-owner For now we'll use github actions but i'll probably use vercel or coolify in the future, also yes @Tr0llie we are going to use ur servers for hosting some stuff in the future such as an LMS
